export { RealEstateMcpClient } from './real-estate.client'
export { McpClientManager } from './client-manager'
export { McpRealEstateAdapter } from './adapters/mcp-real-estate.adapter'
export { REAL_ESTATE_DATA_PORT } from './ports/real-estate-data.port'
export type { IRealEstateDataPort } from './ports/real-estate-data.port'
export type { McpClientConfig, McpToolResult } from './types'
